server:
  port: 1001

spring:
  application:
    name: sct-nacos-payment-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'
