server:
  port: 8001

spring:
  application:
    name: sct-payment-service
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        # 采样率介于0到1之间，1表示全部采集
        probability: 1
  datasource:
#    当前数据源类型
    type: com.alibaba.druid.pool.DruidDataSource
#    mysql驱动包
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/cloud2020?userUnicode=true&characterEncoding=utf-8&useSSL=false

mybatis:
  mapper-locations: classpath:mapper/*.xml
#  所有Entity别名所在包
  type-aliases-package: com.xingpc.sct.entities

eureka:
  client:
    #    表示是否将自己注册进注册中心
    register-with-eureka: true
    #    是否从注册中心拉取已有的注册信息，单点无所谓，集群必须为true，配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #        设置与Eureka交互的服务地址
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8001
    # 是否显示ip
    prefer-ip-address: true
#    # 服务端收到最后一次心跳等待时间上线，默认：90
#    lease-expiration-duration-in-seconds: 2
#    # 客户端向服务端发送心跳时间间隔，默认：30
#    lease-renewal-interval-in-seconds: 1