server:
  port: 9527

spring:
  application:
    name: sct-gateway-service
  cloud:
    gateway:
      routes:
        - id: payment_routh
          uri: lb://sct-payment-service
          predicates:
            - Path=/payment/getPaymentById/**
            - After=2020-05-15T09:16:35.449+08:00[Asia/Shanghai]

        - id: payment_routh2
          uri: lb://sct-payment-service
          predicates:
            - Path=/payment/getPaymentLb/**
            - After=2020-05-15T10:16:35.449+08:00[Asia/Shanghai]
            - Cookie=username,xingpc
            - Header=X-Request-Id, \d+

      # 开启网关动态路由配置
      discovery:
        locator:
          enabled: true
eureka:
  client:
    #    表示是否将自己注册进注册中心
    register-with-eureka: true
    #    是否从注册中心拉取已有的注册信息，单点无所谓，集群必须为true，配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #        设置与Eureka交互的服务地址
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: sct-gateway-service
    # 是否显示ip
    prefer-ip-address: true

